stages:
  - build
  - push
  - deploy-staging
  - deploy-production

before_script:
  # Aktualisiere Stud.IP Quellen
  - svn checkout --username=studip --password=studip --non-interactive svn://develop.studip.de/studip/branches/4.0/ ~/studip40/studip-release/4.0
  # Kopiere Stud.IP Quellen ohne .svn Ordner
  - rsync -aC ~/studip40/studip-release/4.0/ $(pwd)/assets/studip-release/4.0
  # Symlink auf .env file
  - ln -sf ~/studip40/.env .env
  - ln -sfn $(pwd) ~/studip40/main
 
build:
  stage: build
  retry: 2
  tags:
    - studip-staging
  script:
    - ./taskit build

push:
  stage: push
  retry: 2
  tags:
    - studip-staging
  only:
    - master
  script:
    - ./taskit push user=gitlab-ci-token pass=$CI_JOB_TOKEN


deploy-staging:
  stage: deploy-staging
  retry: 2
  tags:
    - studip-staging
  only:
    - master
  environment:
    name: staging
  script:
  # Deploy latest image
    - ./taskit deploy-from-registry user=gitlab-ci-token pass=$CI_JOB_TOKEN services="nginx php-fpm mariadb"
 
