stages:
  - build
  - push
  - deploy-staging
  - deploy-production

before_script:
  # Aktualisiere Stud.IP Quellen
  - svn checkout --username=studip --password=studip --non-interactive svn://develop.studip.de/studip/branches/4.0/ ~/studip40/studip-release/4.0
  # Kopiere Stud.IP Quellen ohne .svn Ordner
  - rsync -aC ~/studip40/studip-release/4.0/ $(pwd)/assets/studip-release/4.0
  # Symlink auf .env file
  - ln -sf ~/studip40/.env .env
  - ln -sfn $(pwd) ~/studip40/main

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  REGISTRY: $CI_REGISTRY_IMAGE

build:
  stage: build
  retry: 2
  tags:
    - studip-staging
  script:
    - docker-compose build

push:
  stage: push
  retry: 2
  tags:
    - studip-staging
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $REGISTRY
    - docker-compose push mariadb nginx php-fpm


deploy-staging:
  stage: deploy-staging
  retry: 2
  tags:
    - studip-staging
  only:
    - master
  environment:
    name: staging
  script:
  # Deploy latest image
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $REGISTRY
    - docker-compose pull
    - docker-compose up -d --no-build $_services
