version: "2"
services:


  php-fpm:
#    image: ${REGISTRY}:php-fpm-7
    build:
      context: .
      dockerfile: php-fpm.dockerfile
      args:
        - TZ=${TIMEZONE}
        - BUILD_NO
        - PHP_FPM_WEB_ROOT
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - BUILD_NO
      - NGINX_SERVER_NAME
      - NGINX_HOST_PORT
      - NGINX_HOST_SSL_PORT
      - NGINX_PROTOCOL
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - PHP_FPM_WEB_ROOT
      - PHP_PM_MAX_CHILDREN
      - PHP_PM_START_SERVERS
      - PHP_PM_MIN_SPARE_SERVERS
      - PHP_PM_MAX_SPARE_SERVERS
      - STUDIP_MAIL_HOST_NAME
      - STUDIP_MAIL_SMTP_SERVER
    volumes:
      - ./volumes/log/php-fpm:/var/log/php
      - ./volumes/studip-data:/usr/local/studip/data


  nginx:
#    image: ${REGISTRY}:nginx-5.1.18
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - TZ=${TIMEZONE}
        - BUILD_NO
        - NGINX_WEB_ROOT
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - BUILD_NO
      - PHP_FPM_PORT=9000
      - NGINX_SERVER_NAME
      - STUDIP_SET_DD_PERMISSION
      - NGINX_SSL_ENABLED
      - NGINX_FORCE_HTTPS
      - NGINX_PROTOCOL
      - NGINX_HOST_PORT
      - NGINX_HOST_SSL_PORT
      - NGINX_WEB_ROOT
      - NGINX_WORKER_PROCESSES
    ports:
      - "${NGINX_HOST_SSL_PORT}:${NGINX_HOST_SSL_PORT}"
      - "${NGINX_HOST_PORT}:${NGINX_HOST_PORT}"
    volumes:
      - ./volumes/log/nginx:/var/log/nginx
      - ./cert/ssl-server:/etc/cert/ssl-server
    links:
      - php-fpm


  mariadb:
#    image: ${REGISTRY}:mariadb:10.0
    build:
        context: .
        dockerfile: mariadb.dockerfile
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#    ports:
#      - "${MYSQL_PORT}:3306"
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./assets/mysql:/etc/mysql/conf.d


  docs:
    image: cogset/mkdocs:latest
    restart: on-failure
    ports:
      - "${DOCS_PORT}:8000"
    volumes:
      - ./docs:/docs/src/docs # For security reasons, do not mount the whole
      - ./mkdocs.yml:/docs/src/mkdocs.yml # directory containing private key

